/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2025-07-28

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "include.h"

#include "debug_log/debug_logs.h"
#include "uart2/uart2.h"
#include "i2c/i2c.h"
#include "system_clock/sysclk.h"
#include "timer/timer.h"
#include "sensor/sgp30/sgp30.h"
#include "sensor/am2302/am2302.h"
#include "sensor/ds1621/ds1621.h"
#include "sensor/lcd1602/lcd1602.h"

typedef struct {
	uint16_t co2;
	uint16_t tvoc;
	float ah; //absolute humidity
} SGP30_Data_t;

typedef struct {
	float tem;
	float hum;
	uint8_t data[4];
} Tem_Hum_Data_t;


/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int Initial();
int LED_Toggle();

int main(void)
{
	char buf[LOG_LENGH]={0};
	Initial();//check_pass(Initial(),"Initial");

	LCD_Init();
	LCD_ClearAll();
	//LCD_GoToXY(0,0);
	//LCD_SendString("Temperature");

	Tem_Hum_Data_t am2302;

	SGP30_Data_t sgp30;
	SGP30_Init();//check_pass(SGP30_Init(),"SGP30_Init");

	Tem_Hum_Data_t ds1621;

  /* Infinite loop */
  while (1)
  {
	  uart2_write_string("---------------------\n\r");
	  LED_Toggle();//check_pass(LED_Toggle(),"LED_Toggle");

	  am2302Request(am2302.data);//check_pass(am2302Request(am2302.data),"am2302Request");
//	check_pass(am2302ShowUart2(am2302.data),"am2302ShowUart2");
	  AM2302_Read_Data(&am2302.hum,&am2302.tem,am2302.data);//check_pass(AM2302_Read_Data(&am2302.hum,&am2302.tem,am2302.data),"AM2302_Read_Data");

	sprintf(buf,"AM2302> TEMP: %d.%d - HUMI: %d.%d\n\r",
			(int)am2302.tem,
			(int)(am2302.tem*10)%10,
			(int)am2302.hum,
			(int)(am2302.hum*10)%10);
	uart2_write_string(buf);


	ds1621_start();//check_pass(ds1621_start(),"ds1621_start");
	ds1621_read_temperature(ds1621.data,2);//check_pass(ds1621_read_temperature(ds1621.data,2),"ds1621_read_temperature");
	ds1621.tem = ds1621.data[0]+ds1621.data[1]/10.0;

	sprintf(buf,"DS1621> TEMP: %d.%d\n\r",
			(int)ds1621.data[0],
			(int)ds1621.data[1]);
	uart2_write_string(buf);


	SGP30_SET_AH(am2302.hum,ds1621.tem,&sgp30.ah);//check_pass(SGP30_SET_AH(am2302.hum,am2302.tem,&sgp30.ah),"SGP30_SET_AH");
	SGP30_Measure(&sgp30.co2,&sgp30.tvoc);//check_pass(SGP30_Measure(&sgp30.co2,&sgp30.tvoc),"SGP30_Measure");
//
	sprintf(buf,"SGP30> CO2: %u - TVOC: %u - AH: %d.%d\n\r",
			sgp30.co2,sgp30.tvoc,
			(int)sgp30.ah,
			(int)(sgp30.ah*10)%10);
	uart2_write_string(buf);


	/*LCD*/
	sprintf(buf,"%d.%d C - %d.%d RH",
				(int)am2302.tem,
				(int)(am2302.tem*10)%10,
				(int)am2302.hum,
				(int)(am2302.hum*10)%10);
	LCD_GoToXY(0,0);
	LCD_SendString(buf);

	sprintf(buf,"%u %u %d.%d",sgp30.co2,sgp30.tvoc,(int)sgp30.ah,(int)(sgp30.ah*10)%10);
	LCD_GoToXY(0,1);
	LCD_SendString(buf);



	/*LED Toggle*/
	GPIOA->ODR = GPIO_ODR_ODR_5;
	systickDelayMs(3000);
  }
  return 0;
}

int Initial(){
	SetSysClk(); //32MHz
	SystemCoreClockUpdate();
	uart2_init();
	I2C1_GPIO_Init();
	I2C1_Init();
	return DONE;
}

/*Pull-up LED*/
int LED_Toggle(){
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	GPIOA->MODER |= GPIO_MODER_MODER5_0;
	GPIOA->ODR &= ~GPIO_ODR_ODR_5;
	return DONE;
}
